
#ifndef BLINKSTICKCPP_EXPORT_H
#define BLINKSTICKCPP_EXPORT_H

#ifdef BLINKSTICKCPP_STATIC_DEFINE
#  define BLINKSTICKCPP_EXPORT
#  define BLINKSTICKCPP_NO_EXPORT
#else
#  ifndef BLINKSTICKCPP_EXPORT
#    ifdef blinkstickcpp_EXPORTS
        /* We are building this library */
#      define BLINKSTICKCPP_EXPORT 
#    else
        /* We are using this library */
#      define BLINKSTICKCPP_EXPORT 
#    endif
#  endif

#  ifndef BLINKSTICKCPP_NO_EXPORT
#    define BLINKSTICKCPP_NO_EXPORT 
#  endif
#endif

#ifndef BLINKSTICKCPP_DEPRECATED
#  define BLINKSTICKCPP_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef BLINKSTICKCPP_DEPRECATED_EXPORT
#  define BLINKSTICKCPP_DEPRECATED_EXPORT BLINKSTICKCPP_EXPORT BLINKSTICKCPP_DEPRECATED
#endif

#ifndef BLINKSTICKCPP_DEPRECATED_NO_EXPORT
#  define BLINKSTICKCPP_DEPRECATED_NO_EXPORT BLINKSTICKCPP_NO_EXPORT BLINKSTICKCPP_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef BLINKSTICKCPP_NO_DEPRECATED
#    define BLINKSTICKCPP_NO_DEPRECATED
#  endif
#endif

#endif /* BLINKSTICKCPP_EXPORT_H */
